Removed minor version pinning of Perfect-HTTP
Perfect-HTTPServer and Perfect-WebSockets have different version requirements to Perfect-HTTP (2.1.* vs 2.0.*). If both Packages are used in the same project a dependency error occurs:

error: The dependency graph could not be satisfied (https://github.com/PerfectlySoft/Perfect-HTTP.git)

This can be fixed by removing the minor version pinning to Perfect-HTTP from Perfect-WebSockets.